// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATIW7b1yAcD2OLeBn77Uivbn7Qiz7uNMs',
    appId: '1:775909615408:web:9f7ae1b2d7f0e4b202caf5',
    messagingSenderId: '775909615408',
    projectId: 'smartgym-af38a',
    authDomain: 'smartgym-af38a.firebaseapp.com',
    storageBucket: 'smartgym-af38a.appspot.com',
    measurementId: 'G-PWT7BMRNT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYekBZg4_3JzFlUsuwP-NTmhIRmR-LHBI',
    appId: '1:775909615408:android:23ae16e69d686f6602caf5',
    messagingSenderId: '775909615408',
    projectId: 'smartgym-af38a',
    storageBucket: 'smartgym-af38a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSbE9PFsE4_Hcy79j6Pp2IejTpNW9mYTY',
    appId: '1:775909615408:ios:0e865b059a5c7c5d02caf5',
    messagingSenderId: '775909615408',
    projectId: 'smartgym-af38a',
    storageBucket: 'smartgym-af38a.appspot.com',
    iosClientId: '775909615408-4884d6k7nipo5dik69igf3spld3unro1.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartgym',
  );
}
